import { describe, expect, it } from 'vitest'

import { applyOperation, type OperationId } from '../operations'
import { parseShapeCode, toShapeCode } from '../shapeCode'
import { HEX_CONFIG, QUAD_CONFIG, operationConfig, type ColorCode } from '../types'

import vectors from './opVectors.json'

interface Vector {
  config: 'quad' | 'hex'
  op: OperationId
  inputs: string[]
  color: string | null
  outputs: string[]
}

const CONFIGS = { quad: QUAD_CONFIG, hex: HEX_CONFIG }

/**
 * These vectors are generated by the official `shapez2` python package, which
 * mirrors the game's own shape logic. Any mismatch means our port drifted.
 * Regenerate with `pnpm gen:vectors`.
 */
describe('operations match the official implementation', () => {
  const byOp = new Map<string, Vector[]>()
  for (const vector of vectors as Vector[]) {
    const key = `${vector.config}/${vector.op}`
    const list = byOp.get(key) ?? []
    list.push(vector)
    byOp.set(key, list)
  }

  for (const [key, cases] of byOp) {
    it(`${key} (${cases.length} cases)`, () => {
      for (const vector of cases) {
        const config = operationConfig(CONFIGS[vector.config], 'normal')
        const inputs = vector.inputs.map((code) => {
          const parsed = parseShapeCode(code, CONFIGS[vector.config])
          if (!parsed.ok) throw new Error(`fixture parse failed: ${code} — ${parsed.error}`)
          return parsed.shape
        })

        const actual = applyOperation(
          vector.op,
          inputs,
          config,
          (vector.color ?? undefined) as ColorCode | undefined,
        ).map(toShapeCode)

        expect(actual, `${vector.op}(${vector.inputs.join(', ')})`).toEqual(vector.outputs)
      }
    })
  }
})
